### ISSUE TITLE
configuration: Tor access to Insight block explorers

### ISSUE THREAD

**Issue by ghost** [satoshilabs/bitcore-deb#5]
Tor access to your Insight block explorers is hindered by your Cloudflare CAPTCHA config.

Cloudflare is returning HTTP 403 CAPTCHA challenges for the Angular.js AJAX requests instead of the content.

Try accessing any of these via Tor and you'll see the problem of mostly blank pages:
https://btc-bitcore1.trezor.io/
https://btc-bitcore1.trezor.io/tx/send
https://btc-bitcore2.trezor.io/
https://btc-bitcore3.trezor.io/
https://ltc-bitcore1.trezor.io/
https://ltc-bitcore2.trezor.io/
https://ltc-bitcore3.trezor.io/
https://bch-bitcore2.trezor.io/
https://btg-bitcore2.trezor.io/

Sorry if this is the wrong place for this issue report.

**Comment by prusnak** [comment]
Why do you need to access our backend servers via Tor?

**Comment by ghost** [comment]
They are convenient. For example, for the recent bitcoin forks, by running these nodes (that can take raw transactions and drop them into a fork's network) you are providing a helpful service to those that just want to dump their airdrop coins (without having to sync a node for that particular fork [which might not be able to find peers from seeds, etc...], or go hunt around for another tx push API). Unfortunately, lots of exchanges depend on P2P propagation and do not have a raw transaction acceptance mechanism.

**Comment by prusnak** [comment]
These nodes are to be used by our users and I plan to keep that way. Once we have enough servers to serve others, we might revisit this.

**Comment by ghost** [comment]
I use TREZOR hardware. I do not use the web wallet interface in its entirety. The CAPTCHA does not prevent use, it just makes it slightly more annoying. Using Tor because mass surveillance sucks. Clearnet is wide open.
