### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by pavlosamonin** [satoshilabs/bitcore-deb#8]
I have downloaded/unpacked main source
in the directory btc and ltc launched makefile and got an error
/root/bitcore-btc/debian/dirs: 1: /root/bitcore-btc/debian/dirs: etc/nginx/sites-available/: not found
/root/bitcore-btc/debian/dirs: 2: /root/bitcore-btc/debian/dirs: usr/local/bin: not found
/root/bitcore-btc/debian/dirs: 3: /root/bitcore-btc/debian/dirs: opt/satoshilabs/bitcore-btc/home/.bitcore/: not found
dh_installdirs: problem reading debian/dirs: 
debian/rules:6: recipe for target 'binary' failed
make: *** [binary] Error 127
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
The command '/bin/sh -c ( cd /root/bitcore-btc && debuild -uc -us )' returned a non-zero code: 29
make: *** [all] Error 29

Any ideas?

**Comment by prusnak** [comment]
This software is obsolete now. Do not use!
