### ISSUE TITLE
Show BCH/BTG as units for Bitcoin Forks

### ISSUE THREAD

**Issue by michal-novacek** [satoshilabs/bitcore-deb#9]
at https://bch-bitcore2.trezor.io/ and https://btg-bitcore2.trezor.io/ etc.

I was also told there would be a design update with Trezor branding! 😉

**Comment by karelbilek** [comment]
yep it is actually done, just needs to be deployed and tested

**Comment by slush0** [comment]
I completely forgot to pull request #7. It's accepted now so we only need to push it to production.

**Comment by yohaaan** [comment]
When USD is chosen as a unit/currency the explorer shows USD balance/amounts according to BTC exchange rate instead of BCH exchange rate. Most likely this is associated with the fact that BTC is set as primary coin/currency.

**Comment by karelbilek** [comment]
@yohaaan thx for noticing. We will probably switch away from bitcore sooner than this is fixed, though. :D

**Comment by prusnak** [comment]
This software is obsolete now. Do not use!
